# PHP Dependencies
#
FROM composer:1.7 as vendor
COPY composer.json composer.json
COPY composer.lock composer.lock
RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist
#
# Frontend
#
FROM node:14 as frontend
RUN mkdir -p /app/public
COPY package.json webpack.mix.js package-lock.json /app/
COPY /resources /app/resources
WORKDIR /app
RUN npm install
RUN npm run dev
#
# Application
#
FROM php:8-fpm-alpine
COPY . /var/www/html
COPY .env.local /var/www/html/.env
COPY --from=vendor /app/vendor/ /var/www/html/vendor/
COPY --from=frontend /app/public/ /var/www/html/public/
#COPY --from=frontend /app/public/css/ /var/www/html/public/css/
COPY --from=frontend /app/mix-manifest.json /var/www/html/mix-manifest.json


RUN addgroup -g 1000 -S www && \
    adduser -u 1000 -S www -G www-data

COPY --chown=www:www-data . /var/www/html
WORKDIR /var/www/html

EXPOSE 1000
CMD [ "php","artisan","serve","--port=1000", "--host=0.0.0.0"]