version: '3'
services:

  #Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
  
    networks:
      - mynet

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    links:
      - app
    depends_on: 
      - app
    networks:
      - mynet
networks:
  mynet:
    driver: bridge